#release configuration
#Sun Mar 22 20:20:12 CET 2026
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.nl.hkstwk\:demo-bom=1.1-SNAPSHOT
project.dev.nl.hkstwk\:demo-distribution=1.1-SNAPSHOT
project.dev.nl.hkstwk\:module-a=1.1-SNAPSHOT
project.dev.nl.hkstwk\:module-b=1.1-SNAPSHOT
project.dev.nl.hkstwk\:multi-module-project=1.1-SNAPSHOT
project.dev.nl.hkstwk\:thirdparty-bom=1.1-SNAPSHOT
project.rel.nl.hkstwk\:demo-bom=1.0
project.rel.nl.hkstwk\:demo-distribution=1.0
project.rel.nl.hkstwk\:module-a=1.0
project.rel.nl.hkstwk\:module-b=1.0
project.rel.nl.hkstwk\:multi-module-project=1.0
project.rel.nl.hkstwk\:thirdparty-bom=1.0
project.scm.nl.hkstwk\:demo-bom.empty=true
project.scm.nl.hkstwk\:demo-distribution.empty=true
project.scm.nl.hkstwk\:module-a.empty=true
project.scm.nl.hkstwk\:module-b.empty=true
project.scm.nl.hkstwk\:multi-module-project.connection=scm\:git\:https\://github.com/hkstwk/multi-module-project.git
project.scm.nl.hkstwk\:multi-module-project.developerConnection=scm\:git\:ssh\://git@github.com/hkstwk/multi-module-project.git
project.scm.nl.hkstwk\:multi-module-project.tag=HEAD
project.scm.nl.hkstwk\:multi-module-project.url=https\://github.com/hkstwk/multi-module-project
project.scm.nl.hkstwk\:thirdparty-bom.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[release]
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=1.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:ssh\://git@github.com/multi-module-project.git
